# File path: .github/workflows/ios-simulator-build.yml
# Purpose: Build an iOS *Simulator* .app, zip it for Appetize, and handle scheme issues.

name: iOS Simulator Build (Appetize)

on:
  workflow_dispatch:
    inputs:
      scheme:
        description: "(Optional) Xcode scheme name, EXACT as shown in xcodebuild -list"
        required: false
        default: ""

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout (full, with LFS & submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name "*.xcworkspace" -print -exec ls -la {} \; || true
          find . -maxdepth 3 -name "*.xcodeproj" -print -exec ls -la {} \; || true

      - name: Detect container (workspace vs project) & list schemes
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          # Prefer workspace if present
          if WORK=$(find . -maxdepth 3 -type d -name "*.xcworkspace" | head -n1); then
            KIND=workspace
            FILE="$WORK"
            echo "Found workspace: $FILE"
            LIST=$(xcodebuild -list -workspace "$FILE" || true)
          elif PROJ=$(find . -maxdepth 3 -type d -name "*.xcodeproj" | head -n1); then
            KIND=project
            FILE="$PROJ"
            echo "Found project: $FILE"
            LIST=$(xcodebuild -list -project "$FILE" || true)
          else
            echo "❌ No .xcodeproj or .xcworkspace found" >&2
            exit 1
          fi
          echo "\n--- xcodebuild -list output ---\n$LIST\n-------------------------------\n"
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "kind=$KIND" >> $GITHUB_OUTPUT
          # Extract first listed scheme (trim)
          FIRST=$(echo "$LIST" | awk '/Schemes:/{flag=1;next}/^$/{flag=0}flag' | sed 's/^\s*//;s/\s*$//' | head -n1)
          echo "first_scheme=$FIRST" >> $GITHUB_OUTPUT

      - name: Resolve Swift Package dependencies (best‑effort)
        run: |
          set -e
          if [ "${{ steps.detect.outputs.kind }}" = "workspace" ]; then
            xcodebuild -resolvePackageDependencies -workspace "${{ steps.detect.outputs.file }}" || true
          else
            xcodebuild -resolvePackageDependencies -project "${{ steps.detect.outputs.file }}" || true
          fi

      - name: Build (iOS Simulator, signing OFF)
        env:
          CONFIG: Release
          SDK: iphonesimulator
          DEST: 'platform=iOS Simulator,name=iPhone 15 Pro'
          DERIVED: ${{ github.workspace }}/build
        run: |
          set -euo pipefail
          SCHEME_INPUT='${{ github.event.inputs.scheme }}'
          if [ -n "$SCHEME_INPUT" ]; then
            SCHEME="$SCHEME_INPUT"
            echo "Using user‑provided scheme: $SCHEME"
          else
            SCHEME='${{ steps.detect.outputs.first_scheme }}'
            echo "Auto‑selected first scheme: $SCHEME"
          fi

          if [ -z "$SCHEME" ]; then
            echo "❌ Could not determine a scheme (none listed)." >&2
            exit 1
          fi

          if [ "${{ steps.detect.outputs.kind }}" = "workspace" ]; then
            xcodebuild \
              -workspace "${{ steps.detect.outputs.file }}" \
              -scheme "$SCHEME" \
              -sdk "$SDK" -configuration "$CONFIG" \
              -destination "$DEST" -derivedDataPath "$DERIVED" \
              CODE_SIGNING_ALLOWED=NO \
              build | tee $GITHUB_WORKSPACE/xcodebuild.log
          else
            xcodebuild \
              -project "${{ steps.detect.outputs.file }}" \
              -scheme "$SCHEME" \
              -sdk "$SDK" -configuration "$CONFIG" \
              -destination "$DEST" -derivedDataPath "$DERIVED" \
              CODE_SIGNING_ALLOWED=NO \
              build | tee $GITHUB_WORKSPACE/xcodebuild.log
          fi

      - name: Zip .app for Appetize
        run: |
          set -euo pipefail
          APP_DIR="$GITHUB_WORKSPACE/build/Build/Products/${CONFIG}-iphonesimulator"
          echo "Looking in: $APP_DIR"
          ls -la "$APP_DIR" || true
          APP_PATH=$(ls -d "$APP_DIR"/*.app 2>/dev/null | head -n1 || true)
          if [ -z "$APP_PATH" ] || [ ! -d "$APP_PATH" ]; then
            echo "❌ No .app found. See build logs above (and xcodebuild.log artifact)." >&2
            exit 1
          fi
          cd "$APP_DIR"
          ZIP_NAME=AppetizeBuild.app.zip
          zip -r "$ZIP_NAME" "$(basename "$APP_PATH")"
          mv "$ZIP_NAME" "$GITHUB_WORKSPACE/"

      - name: Upload artifact (.app.zip and full xcodebuild log)
        uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: |
            AppetizeBuild.app.zip
            xcodebuild.log
